### PR TITLE
BLD: Depend on event-model 1.8.0rc3

### PR DESCRIPTION
**Pull request by danielballan**
I initially stashed a dev branch dependency in ``requirements-dev.txt`` for
expedience. This is the proper solution.

### CODE REVIEW

**Comment by martindurant** [comment]
Do you think it's useful/desirable to have intake-bluesky listed at https://intake.readthedocs.io/en/latest/plugin-directory.html ? 
I'd be keen for the wider world to see the more complex kind of catalogue construction that you have going on.

**Comment by danielballan** [comment]
Yes. Can we add it on Friday? My plan for this week is:

- Publish at least a skeleton of sphinx documentation to explain what this is.
- Create a Binder deployment to illustrate various use cases.

Then, based on those materials, it should be easy to put together a blog post as well, as promised. :-D

**Comment by martindurant** [comment]
Sounds perfect. Are there Intake PRs that you are depending on?

**Comment by danielballan** [comment]
Thanks for asking! Everything we need to make it work was merged in time for 0.4.1, fortunately. I intend to resume work on the the dormant configuration-management PR (https://github.com/ContinuumIO/intake/pull/236) next week --- it's not an urgent need for us, but it is something I would like to contribute soon. Then, the next big thing on my radar is making the server more asynchronous. I have some local experiments on that subject, but nothing yet ready to push.

**Comment by danielballan** [comment]
xref https://github.com/ContinuumIO/intake/pull/268

**Pull request merged**
